language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip setuptools
  - pip install -U six numpy zstandard coveralls boto3
  - pip list
script:
  - coverage run setup.py test
after_success:
  - coveralls
