# Created using the meta.yaml file automatically created using conda-build
# bdist_conda tool

{% set version = "0.6.0" %}

package:
    name: pybgen
    version: {{ version }}

source:
    url: ../dist/pybgen-{{ version }}.tar.gz

build:
    number: 0

requirements:
    host:
        - python {{ python }}.*
        - setuptools
        - numpy >=1.12.0
        - six >=1.10.0
    run:
        - python {{ python }}.*
        - setuptools
        - numpy >=1.12.0
        - six >=1.10.0

test:
    imports:
        - pybgen
        - pybgen.tests

about:
    home: https://github.com/lemieuxl/pybgen
    license: MIT License
    license_family: MIT
    summary: Python module to read BGEN files.

extra:
    copy_test_source_files: true
    final: true
